routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login/{social}','Auth\LoginController@redirectToProvider')->where('social','twitter|facebook|linkedin|google|github|bitbucket');
Route::get('/login/{social}/callback','Auth\LoginController@handleProviderCallback')->where('social','twitter|facebook|linkedin|google|github|bitbucket');

Route::get('/', 'Auth\RegisterController@showRegistrationForm')->name('register');

Auth::routes();
Route::get('logout', 'Auth\LoginController@getLogout')->name('logout');

Route::prefix('account')->middleware(['auth'])->group(function(){
  Route::get('/profile', 'JobProfileController@create')->name('job_profile.add');
  Route::post('/store', 'JobProfileController@store')->name('job_profile.store');

  Route::get('work-history', 'ExperienceController@workHisory');
  Route::resource('experience','ExperienceController');
});

// 2fa Route
Route::get('/2fa/verify', 'Google2FAController@verifyLogin2fa')->name('login.validate');
Route::post('/2fa/login', ['middleware'=>['throttle:3', '2faTimeCheck'], 'uses'=>'Google2FAController@loginWith2fa'])->name('2fa.login');

Route::get('/home', ['middleware'=>['auth', 'setup'], 'uses'=>'HomeController@index'])->name('home');

Route::prefix('settings')->middleware(['auth', 'setup'])->group(function() {

  Route::get('/my-profile', 'JobProfileController@edit')->name('job_profile.edit');
  Route::post('/update', 'JobProfileController@update')->name('job_profile.update');

  Route::get('/2fa/enable', 'Google2FAController@enableTwoFactor')->name('2fa.enable');
  Route::get('/2fa/verify', 'Google2FAController@getValidateToken')->name('2fa.validate');
  Route::post('/auth/verify', ['middleware'=>['throttle:3', '2faTimeCheck'], 'uses'=>'Google2FAController@saveTwoFactor'])->name('2fa.verify');
  Route::post('/2fa/confirm', ['middleware' => ['throttle:3', '2faTimeCheck'], 'uses' => 'Google2FAController@disable2fa'])->name('2fa.disable.verify');
  Route::get('/2fa/disable', 'Google2FAController@disableTwoFactorView')->name('2fa.disable');
  Route::get('/profile', 'SecurityController@profile')->name('profile');
  Route::get('/change-password', 'SecurityController@password')->name('change.password');
  Route::get('/2fa', 'SecurityController@two_factor')->name('two_factor');
  Route::post('/password/change', 'SecurityController@passwordChange')->name('user.change.password');
  Route::get('/access-logs', 'SecurityController@accessLogs')->name('access.logs');
  Route::post('/upload-avatar', 'SecurityController@uploadPicture')->name('upload.picture');
  Route::post('/update-basic', 'SecurityController@storeBasicProfile')->name('update.basic');

});

app/Experience.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Experience extends Model
{
  /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'user_id', 'start_month', 'start_year', 'company_name', 'job_title', 'description', 'country_code',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'user_id',
    ];
}

app/Http/Controllers/ExperienceController.php
<?php

namespace App\Http\Controllers;

use Auth;
use App\Experience;
use Illuminate\Http\Request;

class ExperienceController extends Controller
{

    public function workHisory()
    {
      return view('experience.list');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $experiences = Experience::where('user_id', Auth::user()->id)->latest()->paginate(50);
      return response()->json($experiences);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $request->validate([
        'end_year' => 'required',
      ]);
      $experiences = Experience::create(array_merge($request->all(), ['user_id'=>Auth::user()->id]));
      return response()->json($experiences);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $experiences = Experience::where('user_id', Auth::user()->id)->find($id);
      return response()->json($experiences);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $experiences = Experience::where('user_id', Auth::user()->id)->find($id)->update($request->all());
      return response()->json($experiences);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      Experience::find($id)->delete();
      return response()->json(['done']);
    }
}

resources/views/experience/create.blade.php
<div class="modal fade" id="create-item" tabindex="-1" role="dialog" aria-labelledby="create-item-Label" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <form data-toggle="validator" action="{{ route('experience.store') }}" method="POST">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add Work Experience</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true"><i class="fa fa-close btn btn-outline-danger"></i></span>
        </button>
      </div>

      <div class="modal-body">


          <div class="form-group">
            <div class="material-switch">
              <input id="current_job" name="current_job" type="checkbox" value="1" />
              <label for="current_job" class="bg-success"></label> &nbsp;
              I currently work here
            </div>
          </div>

          <div class="form-group">
            <label class="control-label" for="job_title">Job Title</label>
            <input type="text" name="job_title" id="job_title" class="form-control" data-error="Please enter the position you occupied" required />
            <div class="help-block with-errors"></div>
          </div>

          <div class="form-group">
            <label class="control-label" for="company_name">Company</label>
            <input type="text" name="company_name" id="company_name" class="form-control" data-error="Please enter the position you occupied" required />
            <div class="help-block with-errors"></div>
          </div>

          <div class="form-group">
            <div class="row">
              <div class="col-md-6">
                <label class="control-label" for="company_name">From</label><br>
                  <select name="start_month" id="start_month" class="form-control" data-error="Please select the start month"  required>
                    <option value="">Start Month</option>
                    @for ($i = 1; $i <= 12; $i++)
                      <option value="{{ $i }}">{{ date('F', strtotime($i)) }}</option>
                    @endfor
                  </select>
                  <div class="help-block with-errors "></div>

                  <select name="start_year" id="start_year" class="form-control spacer" data-error="Please select the start year"  required>
                    <option value="">Start Year</option>
                    @for ($i = date('Y'); $i >= date('Y')-65; $i--)
                      <option value="{{ $i }}">{{ $i }}</option>
                    @endfor
                  </select>
                <div class="help-block with-errors "></div>
              </div>

              <div class="col-md-6" id="optional">
                <label class="control-label" for="company_name">To</label><br>
                  <select name="end_month" id="end_month" class="form-control" data-error="Please select the end month"  required>
                    <option value="">End Month</option>
                    @for ($i = 1; $i <= 12; $i++)
                      <option value="{{ $i }}">{{ date('F', strtotime($i)) }}</option>
                    @endfor
                  </select>
                  <div class="help-block with-errors "></div>

                  <select name="end_year" id="end_year" class="form-control spacer" data-error="Please select the end year"  required>
                    <option value="">End Year</option>
                    @for ($i = date('Y'); $i >= date('Y')-65; $i--)
                      <option value="{{ $i }}">{{ $i }}</option>
                    @endfor
                  </select>
                <div class="help-block with-errors "></div>
              </div>

            </div>
          </div>

          <div class="form-group">
            <label class="control-label" for="title">Description:</label>
            <textarea name="details" class="form-control" data-error="Please enter your job description"></textarea>
            <div class="help-block with-errors "></div>
          </div>

      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-secondary pull-left" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn crud-submit btn-success pull-right">Save</button>

      </div>
      </form>
    </div>
  </div>
</div>

resources/views/experience/edit.blade.php
<div class="modal fade" id="edit-item" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">

  <div class="modal-dialog" role="document">

    <div class="modal-content">

      <div class="modal-header">

        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>

        <h4 class="modal-title" id="myModalLabel">Edit Item</h4>

      </div>

      <div class="modal-body">



      		<form data-toggle="validator" action="/experience/14" method="put">

      			<div class="form-group">

					<label class="control-label" for="title">Title:</label>

					<input type="text" name="job_title" class="form-control" data-error="Please enter title." required />

					<div class="help-block with-errors"></div>

				</div>

				<div class="form-group">

					<label class="control-label" for="title">Description:</label>

					<textarea name="company_name" class="form-control" data-error="Please enter details." required></textarea>

					<div class="help-block with-errors"></div>

				</div>

				<div class="form-group">

					<button type="submit" class="btn btn-success crud-submit-edit">Submit</button>

				</div>

      		</form>



      </div>

    </div>

  </div>

</div>

resources/views/experience/list.blade.php
@extends('layouts.app')

@section('content')

<div class="row">

  <div class="col-md-3">
      @include('layouts.partials.my-account-menu')
  </div>

  <div class="col-md-9">

    <div class="col-md-12">

      <div class="card">
          <div class="card-header">{{__('Work Experience')}}</div>

          <div class="card-body">
            @include('layouts.partials.flash-message')

            <div class="progress">
              <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" style="width: 25%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" style="width: 75%">25%</div>
            </div>

            <br>

            <div class="pull-right">
              <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#create-item">
                {{__("Add Work Experience")}}
              </button>
		        </div>
            <br>
            <div id="work-history">
            </div>

          </div>
      </div>
    </div>

  </div>
</div>

@include('experience.create')
@include('experience.edit')

@endsection