routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login/{social}','Auth\LoginController@redirectToProvider')->where('social','twitter|facebook|linkedin|google|github|bitbucket');
Route::get('/login/{social}/callback','Auth\LoginController@handleProviderCallback')->where('social','twitter|facebook|linkedin|google|github|bitbucket');

Route::get('/', 'Auth\RegisterController@showRegistrationForm')->name('register');

Auth::routes();
Route::get('logout', 'Auth\LoginController@getLogout')->name('logout');

Route::prefix('account')->middleware(['auth'])->group(function(){
  Route::get('/profile', 'JobProfileController@create')->name('job_profile.add');
  Route::post('/store', 'JobProfileController@store')->name('job_profile.store');

  Route::get('work-history', 'ExperienceController@workHisory');
  Route::resource('experience','ExperienceController');
});

// 2fa Route
Route::get('/2fa/verify', 'Google2FAController@verifyLogin2fa')->name('login.validate');
Route::post('/2fa/login', ['middleware'=>['throttle:3', '2faTimeCheck'], 'uses'=>'Google2FAController@loginWith2fa'])->name('2fa.login');

Route::get('/home', ['middleware'=>['auth', 'setup'], 'uses'=>'HomeController@index'])->name('home');

Route::prefix('settings')->middleware(['auth', 'setup'])->group(function() {

  Route::get('/my-profile', 'JobProfileController@edit')->name('job_profile.edit');
  Route::post('/update', 'JobProfileController@update')->name('job_profile.update');

  Route::get('/2fa/enable', 'Google2FAController@enableTwoFactor')->name('2fa.enable');
  Route::get('/2fa/verify', 'Google2FAController@getValidateToken')->name('2fa.validate');
  Route::post('/auth/verify', ['middleware'=>['throttle:3', '2faTimeCheck'], 'uses'=>'Google2FAController@saveTwoFactor'])->name('2fa.verify');
  Route::post('/2fa/confirm', ['middleware' => ['throttle:3', '2faTimeCheck'], 'uses' => 'Google2FAController@disable2fa'])->name('2fa.disable.verify');
  Route::get('/2fa/disable', 'Google2FAController@disableTwoFactorView')->name('2fa.disable');
  Route::get('/profile', 'SecurityController@profile')->name('profile');
  Route::get('/change-password', 'SecurityController@password')->name('change.password');
  Route::get('/2fa', 'SecurityController@two_factor')->name('two_factor');
  Route::post('/password/change', 'SecurityController@passwordChange')->name('user.change.password');
  Route::get('/access-logs', 'SecurityController@accessLogs')->name('access.logs');
  Route::post('/upload-avatar', 'SecurityController@uploadPicture')->name('upload.picture');
  Route::post('/update-basic', 'SecurityController@storeBasicProfile')->name('update.basic');

});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">

    {!! Minify::stylesheet([
                  '/css/bootstrap/bootstrap.min.css',
                  '/css/ajax/toastr.min.css',
                  '/css/custom.css'
                ])
    !!}
</head>
<body>
    <div id="app">
        <!--<nav class="navbar navbar-expand-md navbar-light navbar-laravel">-->
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li><a class="btn btn-outline-success my-2 my-sm-0" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                  @if (!in_array(Auth::user()->photo, ["avatar.png", NULL, '']))
                                    <img src="/storage/profile/{{Auth::user()->id}}/{{Auth::user()->photo}}" class="rounded-circle" height="28" alt="{{ Auth::user()->firstname }}">
                                  @else
                                    <img src="/storage/profile/user.png" class="rounded-circle" height="28" alt="{{ Auth::user()->firstname }}">
                                  @endif
                                  {{ Auth::user()->firstname }} <span class="caret"></span>

                                </a>
                                <ul>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                                    <a class="dropdown-item" href="{{ route('profile') }}">
                                      {{__('My Account')}}
                                    </a>

                                    <div class="dropdown-divider"></div>

                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>

                        @endguest
                    </ul>
                </div>

            </div>
        </nav>

        <main class="py-4">
          <div class="container">
            @yield('content')
          </div>
        </main>
    </div>


<!--
    <script
      src="https://code.jquery.com/jquery-3.3.1.js"
      integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
      crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/1000hz-bootstrap-validator/0.11.5/validator.min.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
<link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet">
-->

{!!Minify::javascript([
      '/js/bootstrap/jquery-3.3.1.js',
      '/js/ajax/popper.min.js',
      '/js/bootstrap/bootstrap.min.js',
      '/js/ajax/validator.min.js',
      '/js/ajax/toastr.min.js',
      '/js/custom.js'
      ])
!!}

<script type="text/javascript">
  var url = "<?php echo route('experience.index')?>";
</script>
<script src="/js/experience.js"></script>

</body>
</html>

resources/views/layouts/frontend.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">
    {!! Minify::stylesheet([
                    '/css/app.css',
                    '/css/custom.css'
                ])
    !!}
</head>
<body>
    <div id="app" class="bg">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                          <li>
                          @if(Request::is('login'))
                            <a class="btn btn-outline-success my-2 my-sm-0" href="{{ route('register') }}">{{ __('Register') }}</a>
                          @else
                            <a class="btn btn-outline-success my-2 my-sm-0" href="{{ route('login') }}">{{ __('Login') }}</a>
                          @endif
                          </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                  @if (!in_array(Auth::user()->photo, ["avatar.png", NULL, '']))
                                    <img src="/storage/profile/{{Auth::user()->id}}/{{Auth::user()->photo}}" class="rounded-circle" height="28" alt="{{ Auth::user()->firstname }}">
                                  @else
                                    <img src="/storage/profile/user.png" class="rounded-circle" height="28" alt="{{ Auth::user()->firstname }}">
                                  @endif
                                  {{ Auth::user()->firstname }} <span class="caret"></span>

                                </a>
                                <ul>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                                    <a class="dropdown-item" href="{{ route('profile') }}">
                                      {{__('My Account')}}
                                    </a>

                                    <div class="dropdown-divider"></div>

                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>

                        @endguest
                    </ul>
                </div>

            </div>
        </nav>

        <main class="py-4">
          <div class="container">
            @yield('content')
          </div>
        </main>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
    </div>

    {!!Minify::javascript([
          '/js/app.js',
          '/js/custom.js'
          ])
    !!}
</body>
</html>